import { readdir, readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const failures = [];
const files = await walk(root);
const scripts = files.filter(file => /\.(?:js|mjs)$/.test(file));
for (const filename of scripts) {
  const result = spawnSync(process.execPath, ['--check', filename], { encoding: 'utf8', windowsHide: true });
  if (result.status !== 0) failures.push(`${path.relative(root, filename)}: ${result.stderr || result.error?.message || 'syntax check failed'}`);
}

try {
  const manifest = JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8'));
  if (manifest.manifest_version !== 3) failures.push('manifest.json: manifest_version must be 3');
  const references = [manifest.background?.service_worker, manifest.action?.default_popup, manifest.side_panel?.default_path,
    manifest.options_page, manifest.options_ui?.page, ...Object.values(manifest.icons || {}), ...Object.values(manifest.chrome_url_overrides || {})];
  if (typeof manifest.action?.default_icon === 'string') references.push(manifest.action.default_icon);
  else references.push(...Object.values(manifest.action?.default_icon || {}));
  for (const script of manifest.content_scripts || []) references.push(...(script.js || []), ...(script.css || []));
  for (const reference of references.filter(Boolean)) await verifyAsset(reference, 'manifest.json');
  for (const entry of manifest.web_accessible_resources || []) {
    for (const reference of entry.resources || []) {
      if (reference.includes('*')) {
        const pattern = new RegExp(`^${reference.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*')}$`);
        if (!files.some(file => pattern.test(path.relative(root, file).split(path.sep).join('/')))) failures.push(`manifest.json: no files match ${reference}`);
      } else await verifyAsset(reference, 'manifest.json');
    }
  }
} catch (error) { failures.push(`manifest.json: ${error.message}`); }

for (const filename of files.filter(file => path.extname(file) === '.html')) {
  const html = await readFile(filename, 'utf8');
  const matches = html.matchAll(/\b(?:src|href)\s*=\s*["']([^"']+)["']/gi);
  for (const [, reference] of matches) {
    if (/^(?:[a-z]+:|\/\/|#)/i.test(reference)) continue;
    const clean = reference.split(/[?#]/)[0];
    if (!clean) continue;
    const asset = clean.startsWith('/') ? clean.slice(1) : path.relative(root, path.resolve(path.dirname(filename), clean)).split(path.sep).join('/');
    await verifyAsset(asset, path.relative(root, filename));
  }
}
if (!files.includes(path.join(root, 'index.html'))) failures.push('index.html is missing');

if (failures.length) {
  console.error(failures.join('\n'));
  process.exitCode = 1;
} else console.log(`Verified ${scripts.length} JavaScript modules, manifest assets, and HTML asset references.`);

async function verifyAsset(reference, source) {
  if (typeof reference !== 'string') {
    failures.push(`${source}: invalid asset reference ${String(reference)}`);
    return;
  }
  // Manifest page paths may include a query or hash, while the file itself does not.
  // Keep URL separators distinct from paths generated by Windows path.relative().
  let asset;
  try { asset = decodeURIComponent(reference.split(/[?#]/)[0]); }
  catch { failures.push(`${source}: invalid asset URL ${reference}`); return; }
  if (!asset || path.isAbsolute(asset) || asset.includes('\\') || asset.includes('\0')) {
    failures.push(`${source}: invalid asset reference ${reference}`);
    return;
  }
  const resolved = path.resolve(root, asset);
  if (!resolved.startsWith(`${root}${path.sep}`)) { failures.push(`${source}: asset escapes project root`); return; }
  try { if (!(await stat(resolved)).isFile()) failures.push(`${source}: asset is not a file: ${reference}`); }
  catch { failures.push(`${source}: missing asset ${reference}`); }
}

async function walk(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name === '.git' || entry.name.startsWith('.preview-profile')) continue;
    if (entry.isSymbolicLink()) continue;
    const filename = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(filename));
    else if (entry.isFile()) files.push(filename);
  }
  return files;
}
